apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: spotify
  description: The Spotify web API
  tags:
    - spotify
    - rest
  annotations:
    backstage.io/techdocs-ref: 'url:https://github.com/madhukardevops/backstage'
    # The annotation is deprecated, we use placeholders (see below) instead, remove it later.
    backstage.io/definition-at-location: 'url:https://raw.githubusercontent.com/madhukardevops/openapi-directory/main/APIs/spotify.com/v1/swagger.yaml'
spec:
  type: openapi
  lifecycle: production
  owner: team-a
  definition:
    $text: https://github.com/madhukardevops/openapi-directory/blob/main/APIs/spotify.com/1.0.0/openapi.yaml
